#!/usr/bin/env bun
import { Database } from 'bun:sqlite';
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, symlinkSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join, resolve } from 'node:path';

const PLATFORM_MAP: Record<string, { suffix: string; triple: string }> = {
  'linux:x64': { suffix: 'linux-x64', triple: 'x86_64-unknown-linux-gnu' },
  'linux:arm64': { suffix: 'linux-arm64', triple: 'aarch64-unknown-linux-gnu' },
  'darwin:x64': { suffix: 'darwin-x64', triple: 'x86_64-apple-darwin' },
  'darwin:arm64': { suffix: 'darwin-arm64', triple: 'aarch64-apple-darwin' }
};

const ROOT = resolve(import.meta.dir, '..');
const CONFIG_DIR = join(process.env['XDG_CONFIG_HOME'] ?? join(homedir(), '.config'), 'johto');
const CONFIG_FILE = join(CONFIG_DIR, 'config.toml');
const BIN_DIR = join(homedir(), '.local', 'bin');
const SYMLINK = join(BIN_DIR, 'johto');
const STANDALONE_DIR = join(homedir(), '.local', 'share', 'johto');
const DB_SOURCE = join(ROOT, 'database', 'pokemon-data.sqlite3.db');
const EXAMPLE_DECK = join(ROOT, 'apps', 'deck-cli', 'decks', 'example.toml');

const args = Bun.argv.slice(2);
const standalone = args.includes('--standalone');
const force = args.includes('--force');
const uninstall = args.includes('--uninstall');
const skipE2e = args.includes('--skip-e2e');

let stepNo = 0;
function step(label: string): void {
  stepNo += 1;
  console.log(`\n[${stepNo}] ${label}`);
}
function ok(msg: string): void {
  console.log(`    ✓ ${msg}`);
}
function fail(msg: string, hint?: string): never {
  console.error(`    ✗ ${msg}`);
  if (hint) console.error(`      → ${hint}`);
  process.exit(1);
}

async function run(cmd: string[], cwd = ROOT): Promise<void> {
  const proc = Bun.spawn(cmd, { cwd, stdout: 'inherit', stderr: 'inherit' });
  if ((await proc.exited) !== 0) {
    fail(`command failed: ${cmd.join(' ')}`);
  }
}

async function capture(
  cmd: string[],
  stdin?: string,
  timeoutMs = 120_000
): Promise<{ code: number; stdout: string; stderr: string }> {
  const proc = Bun.spawn(cmd, {
    cwd: ROOT,
    stdin: stdin === undefined ? 'ignore' : new TextEncoder().encode(stdin),
    stdout: 'pipe',
    stderr: 'pipe'
  });

  const timer = setTimeout(() => proc.kill(), timeoutMs);
  const [stdout, stderr, code] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited
  ]);
  clearTimeout(timer);

  return { code, stdout, stderr };
}

/**
 * The e2e gate runs against the *configured default* provider — currently
 * openai — rather than a pinned one, so it exercises the real resolution path
 * including the automatic Anthropic fallback.
 */
function smokeCredential(): { ok: boolean; detail: string } {
  const openai = Boolean(process.env['OPENAI_API_KEY']);
  const anthropic = Boolean(process.env['ANTHROPIC_API_KEY']);
  if (openai) return { ok: true, detail: 'OPENAI_API_KEY set' };
  if (anthropic) return { ok: true, detail: 'ANTHROPIC_API_KEY set (openai will fall back)' };
  return { ok: false, detail: 'neither OPENAI_API_KEY nor ANTHROPIC_API_KEY is set' };
}

function platform(): { suffix: string; triple: string } {
  const key = `${process.platform}:${process.arch}`;
  const entry = PLATFORM_MAP[key];
  if (!entry) {
    fail(
      `unsupported platform ${key}`,
      `supported: ${Object.values(PLATFORM_MAP).map((p) => p.suffix).join(', ')}`
    );
  }
  return entry;
}

function renderConfig(mcpServer: string, cardData: string, decksDir: string): string {
  return [
    '# Generated by scripts/bootstrap-local.ts — re-run with --force to regenerate.',
    '# The Anthropic API key is intentionally absent: resolveApiKey() checks',
    '# ANTHROPIC_API_KEY first, so the secret stays in the environment.',
    '',
    '[paths]',
    `mcp_server = "${mcpServer}"`,
    `card_data = "${cardData}"`,
    `decks_dir = "${decksDir}"`,
    ''
  ].join('\n');
}

function assertConfigMatches(expected: string): void {
  const actual = readFileSync(CONFIG_FILE, 'utf-8');
  if (actual === expected) {
    ok(`config already correct: ${CONFIG_FILE}`);
    return;
  }
  const wanted = expected.split('\n').filter((l) => l.includes(' = '));
  const missing = wanted.filter((l) => !actual.includes(l.trim()));
  if (missing.length === 0) {
    ok(`config has the required paths: ${CONFIG_FILE}`);
    return;
  }
  fail(
    `existing config at ${CONFIG_FILE} does not match this install`,
    `missing: ${missing.map((l) => l.trim()).join(' | ')}  — re-run with --force to overwrite`
  );
}

function doUninstall(): never {
  step('Uninstall');
  if (existsSync(SYMLINK)) {
    rmSync(SYMLINK, { force: true });
    ok(`removed ${SYMLINK}`);
  } else {
    ok(`no symlink at ${SYMLINK}`);
  }
  if (existsSync(CONFIG_FILE)) {
    rmSync(CONFIG_FILE, { force: true });
    ok(`removed ${CONFIG_FILE}`);
  } else {
    ok(`no config at ${CONFIG_FILE}`);
  }
  if (existsSync(STANDALONE_DIR)) {
    rmSync(STANDALONE_DIR, { recursive: true, force: true });
    ok(`removed ${STANDALONE_DIR}`);
  }
  console.log('\nUninstalled. Repository build artifacts were left untouched.');
  process.exit(0);
}

if (uninstall) doUninstall();

const { suffix, triple } = platform();

// Every install path is knowable from the flags alone, so the plan is resolved
// before any build runs — that lets preflight reject a config conflict without
// having already compiled binaries and copied trees.
const cargoBin = join(ROOT, 'apps', 'mcp-server', 'target', 'release', 'pokemon-mcp-server');
const compiledBin = join(ROOT, 'dist-packages', 'cli-platforms', suffix, 'bin', 'johto');
const packedMcp = join(ROOT, 'dist-packages', 'mcp-server-platforms', suffix, 'bin', 'pokemon-mcp-server');

const installedBin = standalone ? join(STANDALONE_DIR, 'bin', 'johto') : compiledBin;
const mcpPath = standalone ? join(STANDALONE_DIR, 'bin', 'pokemon-mcp-server') : cargoBin;
const dbPath = standalone ? join(STANDALONE_DIR, 'card-data', 'pokemon-data.sqlite3.db') : DB_SOURCE;
const decksDir = standalone ? join(homedir(), 'johto', 'decks') : join(ROOT, 'apps', 'deck-cli', 'decks');
const configBody = renderConfig(mcpPath, dbPath, decksDir);

console.log(`johto local bootstrap — ${suffix}${standalone ? ' (standalone)' : ''}`);
console.log(`repo: ${ROOT}`);

// ---------------------------------------------------------------- preflight
step('Preflight');
for (const tool of ['bun', 'cargo']) {
  const found = Bun.which(tool);
  if (!found) fail(`${tool} not found on PATH`);
  ok(`${tool} → ${found}`);
}
if (!existsSync(EXAMPLE_DECK)) fail(`example deck missing: ${EXAMPLE_DECK}`);
ok(`example deck: ${EXAMPLE_DECK}`);
if (existsSync(CONFIG_FILE) && !force) {
  assertConfigMatches(configBody);
} else if (existsSync(CONFIG_FILE)) {
  ok(`existing config will be overwritten (--force): ${CONFIG_FILE}`);
}

// ------------------------------------------------------------- rust sidecar
if (standalone) {
  step(`Build + pack MCP server (${triple}, stripped)`);
  await run(['bash', join(ROOT, 'apps', 'mcp-server', 'build', 'pack-platform.sh'), triple, suffix]);
  ok(`packed → dist-packages/mcp-server-platforms/${suffix}/bin/pokemon-mcp-server`);
} else {
  step('Build MCP server (unstripped, debuggable)');
  await run(['cargo', 'build', '--release', '--manifest-path', join(ROOT, 'apps', 'mcp-server', 'Cargo.toml')]);
  if (!existsSync(cargoBin)) fail(`cargo reported success but ${cargoBin} is missing`);
  ok(cargoBin);
}

// -------------------------------------------------------------- card database
step('Verify card database (read-only — bootstrap never rebuilds)');
if (!existsSync(DB_SOURCE)) {
  fail(
    `card database missing: ${DB_SOURCE}`,
    'bun dist-packages/card-data/scripts/rebuild.ts --source packages/@pokemon-data/data --out database/pokemon-data.sqlite3.db'
  );
}
{
  const db = new Database(DB_SOURCE, { readonly: true });
  const cards = (db.query('SELECT COUNT(*) AS c FROM pokemon_cards').get() as { c: number }).c;
  const sets = (db.query('SELECT COUNT(*) AS c FROM pokemon_card_sets').get() as { c: number }).c;
  db.close();
  if (cards < 1000) fail(`card database looks empty (${cards} cards)`, 'rebuild it with rebuild.ts');
  ok(`${cards} cards, ${sets} sets`);
}

// ----------------------------------------------------------------- compile cli
step(`Compile CLI (${suffix})`);
await run(['bun', join(ROOT, 'apps', 'deck-cli', 'build', 'compile.ts'), suffix]);
if (!existsSync(compiledBin)) fail(`compile reported success but ${compiledBin} is missing`);
ok(compiledBin);

// ------------------------------------------------------------------- install
if (standalone) {
  step('Install standalone tree');
  mkdirSync(dirname(installedBin), { recursive: true });
  mkdirSync(dirname(dbPath), { recursive: true });
  mkdirSync(decksDir, { recursive: true });

  copyFileSync(compiledBin, installedBin);
  copyFileSync(packedMcp, mcpPath);

  // The repo DB runs in WAL mode and may carry uncheckpointed sidecars, so copy
  // all three files rather than risk dropping pages that live only in the WAL.
  copyFileSync(DB_SOURCE, dbPath);
  for (const ext of ['-wal', '-shm']) {
    if (existsSync(DB_SOURCE + ext)) copyFileSync(DB_SOURCE + ext, dbPath + ext);
  }
  ok(`installed → ${STANDALONE_DIR}`);
} else {
  step('Install');
  ok('mode B — symlink points at the in-repo build output');
}

// -------------------------------------------------------------------- config
step('Write config');
mkdirSync(CONFIG_DIR, { recursive: true });
await Bun.write(CONFIG_FILE, configBody);
ok(`wrote ${CONFIG_FILE}`);

// ------------------------------------------------------------------- symlink
step('Link onto PATH');
mkdirSync(BIN_DIR, { recursive: true });
rmSync(SYMLINK, { force: true });
symlinkSync(installedBin, SYMLINK);
ok(`${SYMLINK} → ${installedBin}`);
const onPath = Bun.which('johto');
if (onPath) ok(`resolves on PATH: ${onPath}`);
else console.warn(`    ⚠ ${BIN_DIR} is not on PATH — add: export PATH="${BIN_DIR}:$PATH"`);

// -------------------------------------------------------------- verification
// `--stats --dry-run` exits inside the stats branch (run.ts:124) before the
// prompt is ever built, so the two keyless paths have to be checked separately.
step('Verify (keyless): --dry-run builds the system prompt');
{
  const r = await capture([SYMLINK, 'run', '--deck', EXAMPLE_DECK, '--dry-run']);
  if (r.code !== 0) {
    console.error(r.stdout);
    console.error(r.stderr);
    fail(`exited ${r.code}`);
  }
  if (!r.stdout.includes('SYSTEM PROMPT')) fail('system prompt was not emitted');
  if (!r.stdout.includes('Mega Gardevoir ex')) fail('deck context missing from the prompt');
  ok('MCP spawn, JSON-RPC handshake, load_deck, SQLite enrichment, prompt build');
}

step('Verify (keyless): --stats runs the probability tool');
{
  const r = await capture([SYMLINK, 'run', '--deck', EXAMPLE_DECK, '--stats', '--dry-run']);
  if (r.code !== 0) {
    console.error(r.stdout);
    console.error(r.stderr);
    fail(`exited ${r.code}`);
  }
  if (!r.stdout.includes('Opening hand')) fail('probability table was not emitted');
  ok('analyze_deck_probability round-tripped through the Rust server');
}

if (!skipE2e) {
  step('Verify (end-to-end): one real agent turn (default provider)');
  const credential = smokeCredential();
  if (!credential.ok) {
    console.warn(
      `    ⚠ ${credential.detail} — skipping.\n` +
        '      Export a key, or pass --skip-e2e.'
    );
  } else {
    // No --provider: use the configured default so the gate covers the real
    // resolution path, including falling back to Anthropic if OpenAI is down.
    const prompt = 'In one short sentence: how many Basic Pokemon does this deck run?\nquit\n';
    const r = await capture([SYMLINK, 'run', '--deck', EXAMPLE_DECK], prompt, 300_000);
    if (r.code !== 0) {
      console.error(r.stdout);
      console.error(r.stderr);
      fail(`agent turn exited ${r.code}`);
    }
    if (!r.stdout.includes('Session ended.')) fail('session did not terminate cleanly');
    const provider = /Provider: (\S+) · model: (\S+)/.exec(r.stdout);
    ok(
      provider
        ? `${provider[1]} (${provider[2]}) reached, agent turn completed, session closed`
        : 'agent turn completed, session closed'
    );
  }
}

step('Doctor (advisory — a missing API key makes doctor exit 1 even when the install is fine)');
{
  const r = await capture([SYMLINK, 'doctor']);
  console.log(r.stdout.trimEnd());
  if (r.code !== 0) console.log('    (doctor exited non-zero — see above; not treated as a bootstrap failure)');
}

console.log(`\nDone. \`johto\` is on your PATH${standalone ? '' : ', pointing at the in-repo build'}.`);
console.log('Rebuild after editing the CLI:  bun apps/deck-cli/build/compile.ts ' + suffix);
if (!standalone) console.log('The symlink picks that up immediately — no re-run of this script needed.');
